# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'challenge.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 631, 491))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 160, 200, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_username = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_username_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_username_login.setObjectName("lineEdit_username_login")
        self.verticalLayout_2.addWidget(self.lineEdit_username_login)
        self.lineEdit_password_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password_login.setObjectName("lineEdit_password_login")
        self.verticalLayout_2.addWidget(self.lineEdit_password_login)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.button_login = QtWidgets.QPushButton(self.page)
        self.button_login.setGeometry(QtCore.QRect(280, 230, 75, 23))
        self.button_login.setObjectName("button_login")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(250, 290, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setObjectName("label")
        self.button_createOne = QtWidgets.QPushButton(self.page)
        self.button_createOne.setGeometry(QtCore.QRect(280, 320, 75, 23))
        self.button_createOne.setObjectName("button_createOne")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.button_signup = QtWidgets.QPushButton(self.page_2)
        self.button_signup.setGeometry(QtCore.QRect(280, 280, 75, 23))
        self.button_signup.setObjectName("button_signup")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 120, 231, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_username_signup = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_username_signup.setObjectName("lineEdit_username_signup")
        self.gridLayout_3.addWidget(self.lineEdit_username_signup, 2, 1, 1, 1)
        self.lineEdit_lastName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.gridLayout_3.addWidget(self.lineEdit_lastName, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 4, 1)
        self.lineEdit_password_signup = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_password_signup.setObjectName("lineEdit_password_signup")
        self.gridLayout_3.addWidget(self.lineEdit_password_signup, 3, 1, 1, 1)
        self.lineEdit_firstName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.gridLayout_3.addWidget(self.lineEdit_firstName, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.button_logout = QtWidgets.QPushButton(self.page_3)
        self.button_logout.setGeometry(QtCore.QRect(270, 400, 75, 23))
        self.button_logout.setObjectName("button_logout")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(0, 370, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_tanksNumber = QtWidgets.QLabel(self.page_3)
        self.label_tanksNumber.setGeometry(QtCore.QRect(110, 370, 47, 13))
        self.label_tanksNumber.setAutoFillBackground(False)
        self.label_tanksNumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_tanksNumber.setText("")
        self.label_tanksNumber.setObjectName("label_tanksNumber")
        self.label_cameraFeed = QtWidgets.QLabel(self.page_3)
        self.label_cameraFeed.setGeometry(QtCore.QRect(110, 40, 401, 221))
        self.label_cameraFeed.setText("")
        self.label_cameraFeed.setObjectName("label_cameraFeed")
        self.layoutWidget2 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 310, 221, 48))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_temp = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_temp.setObjectName("lineEdit_temp")
        self.gridLayout_4.addWidget(self.lineEdit_temp, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_ph = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_ph.setObjectName("lineEdit_ph")
        self.gridLayout_4.addWidget(self.lineEdit_ph, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(480, 280, 141, 83))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_holes = QtWidgets.QPushButton(self.layoutWidget3)
        self.button_holes.setObjectName("button_holes")
        self.verticalLayout_3.addWidget(self.button_holes)
        self.button_pipe = QtWidgets.QPushButton(self.layoutWidget3)
        self.button_pipe.setObjectName("button_pipe")
        self.verticalLayout_3.addWidget(self.button_pipe)
        self.button_cleaning = QtWidgets.QPushButton(self.layoutWidget3)
        self.button_cleaning.setObjectName("button_cleaning")
        self.verticalLayout_3.addWidget(self.button_cleaning)
        self.layoutWidget4 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(380, 290, 79, 54))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_analyzeTanks = QtWidgets.QPushButton(self.layoutWidget4)
        self.button_analyzeTanks.setObjectName("button_analyzeTanks")
        self.verticalLayout_4.addWidget(self.button_analyzeTanks)
        self.button_createTank = QtWidgets.QPushButton(self.layoutWidget4)
        self.button_createTank.setObjectName("button_createTank")
        self.verticalLayout_4.addWidget(self.button_createTank)
        self.button_update = QtWidgets.QPushButton(self.page_3)
        self.button_update.setGeometry(QtCore.QRect(50, 400, 75, 23))
        self.button_update.setObjectName("button_update")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(250, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.button_main_analyze = QtWidgets.QPushButton(self.page_4)
        self.button_main_analyze.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.button_main_analyze.setObjectName("button_main_analyze")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(250, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.button_main_create = QtWidgets.QPushButton(self.page_5)
        self.button_main_create.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.button_main_create.setObjectName("button_main_create")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.buttonsConnections()
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_username.setText(_translate("MainWindow", "Username :"))
        self.label_password.setText(_translate("MainWindow", "Password :"))
        self.button_login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Don\'t have an account? "))
        self.button_createOne.setText(_translate("MainWindow", "Create one!"))
        self.button_signup.setText(_translate("MainWindow", "Signup"))
        self.label_4.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "First Name:"))
        self.label_3.setText(_translate("MainWindow", "Last Name:"))
        self.label_5.setText(_translate("MainWindow", "Password:"))
        self.button_logout.setText(_translate("MainWindow", "Logout"))
        self.label_8.setText(_translate("MainWindow", "Number of Tanks:"))
        self.label_6.setText(_translate("MainWindow", "Temperature:"))
        self.label_7.setText(_translate("MainWindow", "PH:"))
        self.button_holes.setText(_translate("MainWindow", "Inspect fishnet holes "))
        self.button_pipe.setText(_translate("MainWindow", "Inspect pipe"))
        self.button_cleaning.setText(_translate("MainWindow", "Inspect fishnet for cleaning"))
        self.button_analyzeTanks.setText(_translate("MainWindow", "Analyze Tanks"))
        self.button_createTank.setText(_translate("MainWindow", "Create Tank"))
        self.button_update.setText(_translate("MainWindow", "Update"))
        self.label_9.setText(_translate("MainWindow", "Analyze Tanks"))
        self.button_main_analyze.setText(_translate("MainWindow", "Main Page"))
        self.label_10.setText(_translate("MainWindow", "Create Tanks"))
        self.button_main_create.setText(_translate("MainWindow", "Main Page"))



    def loginIsClicked(self):

        username_login=self.lineEdit_username_login.text()
        password_login=self.lineEdit_password_login.text()
        self.stackedWidget.setCurrentIndex(2)

    def createOneIsClicked(self):

        self.stackedWidget.setCurrentIndex(1)

    def signupIsClicked(self):

        firstName=self.lineEdit_firstName.text()
        lastName=self.lineEdit_lastName.text()
        username_signup=self.lineEdit_username_signup.text()
        password_signup=self.lineEdit_password_signup.text()
        self.stackedWidget.setCurrentIndex(0)


    def getBackToLogin(self):

        self.stackedWidget.setCurrentIndex(0)

    def analyzeTanksIsClicked(self):

        self.stackedWidget.setCurrentIndex(3)

    def createTankIsClicked(self):

        self.stackedWidget.setCurrentIndex(4)

    def getBackToMainPage(self):

        self.stackedWidget.setCurrentIndex(2)

    def updateReadings(self):

        temp=self.lineEdit_temp.text()
        ph=self.lineEdit_ph.text()

    def buttonsConnections(self):

        self.button_login.clicked.connect(self.loginIsClicked)
        self.button_createOne.clicked.connect(self.createOneIsClicked)
        self.button_signup.clicked.connect(self.signupIsClicked)
        self.button_logout.clicked.connect(self.getBackToLogin)
        self.button_analyzeTanks.clicked.connect(self.analyzeTanksIsClicked)
        self.button_createTank.clicked.connect(self.createTankIsClicked)
        self.button_main_analyze.clicked.connect(self.getBackToMainPage)
        self.button_main_create.clicked.connect(self.getBackToMainPage)
        self.button_update.clicked.connect(self.updateReadings)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
