# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'challenge.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 631, 491))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.layoutWidget = QtWidgets.QWidget(self.page_login)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 160, 200, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_username = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_username_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_username_login.setObjectName("lineEdit_username_login")
        self.verticalLayout_2.addWidget(self.lineEdit_username_login)
        self.lineEdit_password_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password_login.setObjectName("lineEdit_password_login")
        self.verticalLayout_2.addWidget(self.lineEdit_password_login)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.button_login = QtWidgets.QPushButton(self.page_login)
        self.button_login.setGeometry(QtCore.QRect(280, 230, 75, 23))
        self.button_login.setObjectName("button_login")
        self.label = QtWidgets.QLabel(self.page_login)
        self.label.setGeometry(QtCore.QRect(250, 290, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setObjectName("label")
        self.button_createOne = QtWidgets.QPushButton(self.page_login)
        self.button_createOne.setGeometry(QtCore.QRect(280, 320, 75, 23))
        self.button_createOne.setObjectName("button_createOne")
        self.stackedWidget.addWidget(self.page_login)
        self.page_signup = QtWidgets.QWidget()
        self.page_signup.setObjectName("page_signup")
        self.button_signup = QtWidgets.QPushButton(self.page_signup)
        self.button_signup.setGeometry(QtCore.QRect(280, 280, 75, 23))
        self.button_signup.setObjectName("button_signup")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_signup)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 120, 231, 128))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_firstName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.verticalLayout_10.addWidget(self.lineEdit_firstName)
        self.lineEdit_lastName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.verticalLayout_10.addWidget(self.lineEdit_lastName)
        self.lineEdit_username_signup = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_username_signup.setObjectName("lineEdit_username_signup")
        self.verticalLayout_10.addWidget(self.lineEdit_username_signup)
        self.lineEdit_password_signup = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_password_signup.setObjectName("lineEdit_password_signup")
        self.verticalLayout_10.addWidget(self.lineEdit_password_signup)
        self.lineEdit_email_signup = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_email_signup.setObjectName("lineEdit_email_signup")
        self.verticalLayout_10.addWidget(self.lineEdit_email_signup)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_signup)
        self.page_mainPage = QtWidgets.QWidget()
        self.page_mainPage.setObjectName("page_mainPage")
        self.button_logout = QtWidgets.QPushButton(self.page_mainPage)
        self.button_logout.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.button_logout.setObjectName("button_logout")
        self.label_displayName = QtWidgets.QLabel(self.page_mainPage)
        self.label_displayName.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.label_displayName.setText("")
        self.label_displayName.setObjectName("label_displayName")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_mainPage)
        self.stackedWidget_2.setGeometry(QtCore.QRect(140, 50, 431, 361))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_blank = QtWidgets.QWidget()
        self.page_blank.setObjectName("page_blank")
        self.stackedWidget_2.addWidget(self.page_blank)
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 70, 234, 76))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_13.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_13.addWidget(self.label_29)
        self.gridLayout_7.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_fishType_tank = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_fishType_tank.setObjectName("lineEdit_fishType_tank")
        self.verticalLayout_14.addWidget(self.lineEdit_fishType_tank)
        self.lineEdit_harvestDate_tank = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_harvestDate_tank.setObjectName("lineEdit_harvestDate_tank")
        self.verticalLayout_14.addWidget(self.lineEdit_harvestDate_tank)
        self.lineEdit_nextFeeding = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_nextFeeding.setObjectName("lineEdit_nextFeeding")
        self.verticalLayout_14.addWidget(self.lineEdit_nextFeeding)
        self.gridLayout_7.addLayout(self.verticalLayout_14, 0, 1, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget_4.setGeometry(QtCore.QRect(230, 440, 158, 26))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.layoutWidget_5 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget_5.setGeometry(QtCore.QRect(260, 100, 141, 64))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_15.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_15.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_15.addWidget(self.label_32)
        self.gridLayout_8.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_cleaning_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_cleaning_2.setText("")
        self.label_cleaning_2.setObjectName("label_cleaning_2")
        self.verticalLayout_16.addWidget(self.label_cleaning_2)
        self.label_holes_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_holes_2.setObjectName("label_holes_2")
        self.verticalLayout_16.addWidget(self.label_holes_2)
        self.label_pipes_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_pipes_2.setText("")
        self.label_pipes_2.setObjectName("label_pipes_2")
        self.verticalLayout_16.addWidget(self.label_pipes_2)
        self.gridLayout_8.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 170, 221, 48))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_9.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEdit_temp = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_temp.setObjectName("lineEdit_temp")
        self.gridLayout_9.addWidget(self.lineEdit_temp, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 1, 0, 1, 1)
        self.lineEdit_ph = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_ph.setObjectName("lineEdit_ph")
        self.gridLayout_9.addWidget(self.lineEdit_ph, 1, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget2.setGeometry(QtCore.QRect(110, 30, 161, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.layoutWidget3 = QtWidgets.QWidget(self.page_dashboard)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 290, 158, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_emailPath = QtWidgets.QPushButton(self.layoutWidget3)
        self.button_emailPath.setObjectName("button_emailPath")
        self.horizontalLayout_4.addWidget(self.button_emailPath)
        self.button_subscribe = QtWidgets.QPushButton(self.layoutWidget3)
        self.button_subscribe.setObjectName("button_subscribe")
        self.horizontalLayout_4.addWidget(self.button_subscribe)
        self.stackedWidget_2.addWidget(self.page_dashboard)
        self.page_analyzeTanks = QtWidgets.QWidget()
        self.page_analyzeTanks.setObjectName("page_analyzeTanks")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_analyzeTanks)
        self.layoutWidget4.setGeometry(QtCore.QRect(70, 120, 281, 85))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.button_cleaning_2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.button_cleaning_2.setObjectName("button_cleaning_2")
        self.verticalLayout_17.addWidget(self.button_cleaning_2)
        self.button_holes_2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.button_holes_2.setObjectName("button_holes_2")
        self.verticalLayout_17.addWidget(self.button_holes_2)
        self.button_pipe_2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.button_pipe_2.setObjectName("button_pipe_2")
        self.verticalLayout_17.addWidget(self.button_pipe_2)
        self.gridLayout_10.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_cleaning2 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cleaning2.setFont(font)
        self.label_cleaning2.setText("")
        self.label_cleaning2.setObjectName("label_cleaning2")
        self.verticalLayout_18.addWidget(self.label_cleaning2)
        self.label_holes2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_holes2.setText("")
        self.label_holes2.setObjectName("label_holes2")
        self.verticalLayout_18.addWidget(self.label_holes2)
        self.label_pipe2 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_pipe2.setFont(font)
        self.label_pipe2.setText("")
        self.label_pipe2.setObjectName("label_pipe2")
        self.verticalLayout_18.addWidget(self.label_pipe2)
        self.gridLayout_10.addLayout(self.verticalLayout_18, 0, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_analyzeTanks)
        self.page_createTank = QtWidgets.QWidget()
        self.page_createTank.setObjectName("page_createTank")
        self.button_main_create = QtWidgets.QPushButton(self.page_createTank)
        self.button_main_create.setGeometry(QtCore.QRect(160, 250, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_main_create.setFont(font)
        self.button_main_create.setObjectName("button_main_create")
        self.layoutWidget_7 = QtWidgets.QWidget(self.page_createTank)
        self.layoutWidget_7.setGeometry(QtCore.QRect(60, 50, 319, 154))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_fishType_create = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_fishType_create.setObjectName("lineEdit_fishType_create")
        self.verticalLayout_8.addWidget(self.lineEdit_fishType_create)
        self.lineEdit_feedingSchedule = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_feedingSchedule.setObjectName("lineEdit_feedingSchedule")
        self.verticalLayout_8.addWidget(self.lineEdit_feedingSchedule)
        self.lineEdit_wqThreshold = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_wqThreshold.setObjectName("lineEdit_wqThreshold")
        self.verticalLayout_8.addWidget(self.lineEdit_wqThreshold)
        self.lineEdit_tempLThreshold = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_tempLThreshold.setObjectName("lineEdit_tempLThreshold")
        self.verticalLayout_8.addWidget(self.lineEdit_tempLThreshold)
        self.lineEdit_tempUThreshold = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_tempUThreshold.setObjectName("lineEdit_tempUThreshold")
        self.verticalLayout_8.addWidget(self.lineEdit_tempUThreshold)
        self.lineEdit_harvestDate_create = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_harvestDate_create.setObjectName("lineEdit_harvestDate_create")
        self.verticalLayout_8.addWidget(self.lineEdit_harvestDate_create)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_createTank)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.label_8 = QtWidgets.QLabel(self.page_settings)
        self.label_8.setGeometry(QtCore.QRect(190, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget_2.addWidget(self.page_settings)
        self.layoutWidget5 = QtWidgets.QWidget(self.page_mainPage)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 190, 79, 131))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_dashboard = QtWidgets.QPushButton(self.layoutWidget5)
        self.button_dashboard.setObjectName("button_dashboard")
        self.verticalLayout_4.addWidget(self.button_dashboard)
        self.button_createTank = QtWidgets.QPushButton(self.layoutWidget5)
        self.button_createTank.setObjectName("button_createTank")
        self.verticalLayout_4.addWidget(self.button_createTank)
        self.button_analyzeTanks = QtWidgets.QPushButton(self.layoutWidget5)
        self.button_analyzeTanks.setObjectName("button_analyzeTanks")
        self.verticalLayout_4.addWidget(self.button_analyzeTanks)
        self.button_settings = QtWidgets.QPushButton(self.layoutWidget5)
        self.button_settings.setObjectName("button_settings")
        self.verticalLayout_4.addWidget(self.button_settings)
        self.stackedWidget.addWidget(self.page_mainPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.numberOfTanks=1
        self.buttonsConnections()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_username.setText(_translate("MainWindow", "Username :"))
        self.label_password.setText(_translate("MainWindow", "Password :"))
        self.button_login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Don\'t have an account? "))
        self.button_createOne.setText(_translate("MainWindow", "Create one!"))
        self.button_signup.setText(_translate("MainWindow", "Signup"))
        self.label_2.setText(_translate("MainWindow", "First Name:"))
        self.label_3.setText(_translate("MainWindow", "Last Name:"))
        self.label_4.setText(_translate("MainWindow", "Username:"))
        self.label_5.setText(_translate("MainWindow", "Password:"))
        self.label_20.setText(_translate("MainWindow", "Email Address:"))
        self.button_logout.setText(_translate("MainWindow", "Logout"))
        self.label_26.setText(_translate("MainWindow", "Fish Type:"))
        self.label_28.setText(_translate("MainWindow", "Harvest Date:"))
        self.label_29.setText(_translate("MainWindow", "Next Feeding in:"))
        self.lineEdit_nextFeeding.setText(_translate("MainWindow", "6:00:00"))
        self.pushButton_3.setText(_translate("MainWindow", "Email path"))
        self.pushButton_4.setText(_translate("MainWindow", "Subscribe"))
        self.label_30.setText(_translate("MainWindow", "Cleaning:"))
        self.label_31.setText(_translate("MainWindow", "Holes:"))
        self.label_32.setText(_translate("MainWindow", "Pipes:"))
        self.label_holes_2.setText(_translate("MainWindow", "l"))
        self.label_33.setText(_translate("MainWindow", "Temperature:"))
        self.label_34.setText(_translate("MainWindow", "PH:"))
        self.label_35.setText(_translate("MainWindow", "Choose a tank!"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Tank 1"))
        self.button_emailPath.setText(_translate("MainWindow", "Email path"))
        self.button_subscribe.setText(_translate("MainWindow", "Subscribe"))
        self.button_cleaning_2.setText(_translate("MainWindow", "Inspect fishnet for cleaning"))
        self.button_holes_2.setText(_translate("MainWindow", "Inspect fishnet holes "))
        self.button_pipe_2.setText(_translate("MainWindow", "Inspect pipe"))
        self.button_main_create.setText(_translate("MainWindow", "Create a Tank!"))
        self.label_14.setText(_translate("MainWindow", "Fish type:"))
        self.label_15.setText(_translate("MainWindow", "Feeding schedule:"))
        self.label_16.setText(_translate("MainWindow", "Water quality threshold:"))
        self.label_17.setText(_translate("MainWindow", "Temperature lower threshold:"))
        self.label_18.setText(_translate("MainWindow", "Temperature upper threshold:"))
        self.label_19.setText(_translate("MainWindow", "Harverst date:"))
        self.label_8.setText(_translate("MainWindow", "Settings"))
        self.button_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.button_createTank.setText(_translate("MainWindow", "Create Tank"))
        self.button_analyzeTanks.setText(_translate("MainWindow", "Analyze Tanks"))
        self.button_settings.setText(_translate("MainWindow", "Settings"))



    def loginIsClicked(self):

        username_login=self.lineEdit_username_login.text()
        password_login=self.lineEdit_password_login.text()
        self.stackedWidget.setCurrentIndex(2)
        text = "Welcome," + username_login
        self.label_displayName.setText(text)

    def createOneIsClicked(self):
        
        self.stackedWidget.setCurrentIndex(1)

    def signupIsClicked(self):
        
        firstName=self.lineEdit_firstName.text()
        lastName=self.lineEdit_lastName.text()
        username_signup=self.lineEdit_username_signup.text()
        password_signup=self.lineEdit_password_signup.text()
        email_signup=self.lineEdit_email_signup.text()
        
        self.stackedWidget.setCurrentIndex(0)


    def getBackToLogin(self):
        
        self.stackedWidget.setCurrentIndex(0)

    def analyzeTanksIsClicked(self):
        
        self.stackedWidget_2.setCurrentIndex(2)

    def createTankIsClicked(self):
        
        self.stackedWidget_2.setCurrentIndex(3)

    def settingsIsClicked(self):
        
        self.stackedWidget_2.setCurrentIndex(4)

    def dashboardIsClicked(self):
        
        self.stackedWidget_2.setCurrentIndex(1)

    def getBackToMainPage(self):
        
        self.stackedWidget.setCurrentIndex(2)

    def updateReadings(self):
        
        temp=self.lineEdit_temp.text()
        ph=self.lineEdit_ph.text()

    def subscribeIsClicked(self):
        
        if self.button_subscribe.text() == "Show report" :
            print("Send email")

        self.button_subscribe.setText("Show report")




    def createTank(self):
        
        fishType = self.lineEdit_fishType_create.text()
        feedingSchedule = self.lineEdit_feedingSchedule.text()
        waterQualityThreshold = self.lineEdit_wqThreshold.text()
        temperatureLowerThresholdd = self.lineEdit_tempLThreshold.text()
        temperatureUpperThreshold = self.lineEdit_tempUThreshold.text()
        harvestDate = self.lineEdit_harvestDate_create.text()
                
        self.numberOfTanks=self.numberOfTanks+1
        text = "Tank " + str(self.numberOfTanks) 
        self.comboBox.addItem(text)


                
    def buttonsConnections(self):
        
        self.button_login.clicked.connect(self.loginIsClicked)
        self.button_createOne.clicked.connect(self.createOneIsClicked)
        self.button_signup.clicked.connect(self.signupIsClicked)
        self.button_logout.clicked.connect(self.getBackToLogin)
        self.button_analyzeTanks.clicked.connect(self.analyzeTanksIsClicked)
        self.button_createTank.clicked.connect(self.createTankIsClicked)
        self.button_settings.clicked.connect(self.settingsIsClicked)
        self.button_dashboard.clicked.connect(self.dashboardIsClicked)
        self.button_main_create.clicked.connect(self.createTank)
        self.button_subscribe.clicked.connect(self.subscribeIsClicked)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
